dashboard/urls.py
from django.urls import path
from .import views
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee urls
    path('employees/all/',views.dashboard_employees, name='employees'),
    path('employee/create/',views.dashboard_employees_create, name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info, name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data, name='edit'),

    # # Emergency
    path('emergency/create/',views.dashboard_emergency_create,name='emergencycreate'),
    # path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),
    path('emergency/', views.dashboard_emergency, name='emergency'),  # URL for viewing emergency information

    # # Family
    path('family/create/',views.dashboard_family_create,name='familycreate'),
    # path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    path('dashboard/family/', views.dashboard_family, name='family'),
    # #Bank
    path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),
    path('bank/', dashboard_bank_detail, name='bank'),  # URL pattern for bank details
    path('dashboard/bank/create/', views.dashboard_bank_create, name='bankcreate'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),

    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/all/view/<int:id>/', views.leaves_view, name='userleaveview'),

    # path('leaves/recommended-view/all/',views.pending_recommendation,name='recommendlist'),

   
    #Approve Leave
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'), 

    #used to display the recommended status of the leave
    path('leave/recommend/<int:id>/', views.recommend_leave,name='userleaverecommend'), 
    path('leaves/recommended/all/',views.recommended_leave_list,name='recommendedleavelist'), #very perfect
    # path('leave/unrecommendleave/<int:id>/',views.unrecommend_leave,name='userunrecommendleave'),#very perfect
    path('leaves/recommend/view/<int:id>/',views.recommend_view,name='userrecommendview'),
    # path('leave/unrecommended/all',views.Unrecommend_list,name='unrecommendedleavelist'),
# recommend_view
    
    # path('leaves/recommend/view/<int:id>/',views.recommend_view,name='recommendview'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),


    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    path('leave/edit/<int:id>/', views.edit_leave, name='edit_leave'),

    path('leave/update_leave_end_date/<int:id>/', views.update_leave_end_date, name='update_leave_end_date'),
    path('leave/<int:id>/add_holiday/', views.add_holiday_view, name='add_holiday'),


    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),



]

hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Leave Management System Admin'

dashboard/models.py
from django.db import models
# Create your models here.

dashboard/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
import datetime
from django.contrib.auth.decorators import user_passes_test
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from employee.forms import EmployeeCreateForm
from leave.models import Leave
from employee.models import *
from leave.forms import LeaveCreationForm
from datetime import date


def dashboard(request):
    dataset = dict()
    user = request.user
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    employees = Employee.objects.all()
    leaves = Leave.objects.all_pending_leaves()
    leavey = Leave.objects.all_recommended_leaves()
    staff_leaves = Leave.objects.filter(user=user)
    dataset['employees'] = employees
    dataset['leaves'] = leaves
    dataset['leavey'] = leavey
    dataset['staff_leaves'] = staff_leaves
    dataset['title'] = 'summary'

    return render(request, 'dashboard/dashboard_index.html', dataset)


from django.shortcuts import render


def dashboard_employees(request):
    if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
        return redirect('/')

    dataset = dict()
    departments = Department.objects.all()
    employees = Employee.objects.all()
    dashboard_family = Family.objects.all()

    # Pagination
    query = request.GET.get('search')
    if query:
        employees = employees.filter(
            Q(firstname__icontains=query) |
            Q(lastname__icontains=query)
        )

    paginator = Paginator(employees, 10)  # Show 10 employee lists per page
    page = request.GET.get('page')
    employees_paginated = paginator.get_page(page)

    # Include employees in the dataset
    # dataset['employees'] = employees_paginated
    dataset['employees'] = employees
    dataset['dashboard_family'] = dashboard_family

    blocked_employees = Employee.objects.all_blocked_employees()

    return render(request, 'dashboard/employee_app.html', dataset)


from django.shortcuts import render, redirect
from django.contrib import messages


# from .forms import EmployeeCreateForm
# from .models import Employee, Role, Department
# from django.contrib.auth.models import User

# def dashboard_employees_create(request):
#     if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
#         return redirect('/')
#
#     if request.method == 'POST':
#         form = EmployeeCreateForm(request.POST, request.FILES)
#         if form.is_valid():
#             instance = form.save(commit=False)
#
#             # Fetch the user instance and assign it to the employee
#             user_id = request.POST.get('user')
#             assigned_user = User.objects.get(id=user_id)
#             instance.user = assigned_user
#
#             # Assign other fields directly from the form data
#             instance.title = request.POST.get('title')
#             instance.image = request.FILES.get('image')
#             instance.firstname = request.POST.get('firstname')
#             instance.lastname = request.POST.get('lastname')
#             instance.othername = request.POST.get('othername')
#             instance.birthday = request.POST.get('birthday')
#
#             # Fetch and assign the role instance
#             role_id = request.POST.get('role')
#             role_instance = Role.objects.get(id=role_id)
#             instance.role = role_instance
#
#             instance.startdate = request.POST.get('startdate')
#             instance.employeetype = request.POST.get('employeetype')
#             instance.employeeid = request.POST.get('employeeid')
#             instance.dateissued = request.POST.get('dateissued')
#
#             # Fetch and assign the department instance
#             department_id = request.POST.get('designation')
#             department_instance = Department.objects.get(id=department_id)
#             instance.designation = department_instance
#
#             instance.save()
#             messages.success(request, 'Employee successfully created ', extra_tags='alert alert-warning alert-dismissible show')
#             return redirect('dashboard:employees')
#         else:
#             messages.error(request, 'Trying to create duplicate employees with a single user account ', extra_tags='alert alert-warning alert-dismissible show')
#             return redirect('dashboard:employeecreate')
#
#     dataset = {'form': EmployeeCreateForm(), 'title': 'register employee'}
#     return render(request, 'dashboard/employee_create.html', dataset)
#
#


def dashboard_employees_create(request):
    if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
        return redirect('/')

    if request.method == 'POST':
        form = EmployeeCreateForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            user = request.POST.get('user')
            assigned_user = User.objects.get(id=user)

            instance.user = assigned_user

            instance.title = request.POST.get('title')
            instance.image = request.FILES.get('image')
            instance.firstname = request.POST.get('firstname')
            instance.lastname = request.POST.get('lastname')
            instance.othername = request.POST.get('othername')

            instance.birthday = request.POST.get('birthday')

            role = request.POST.get('role')
            role_instance = Role.objects.get(id=role)
            instance.role = role_instance

            instance.startdate = request.POST.get('startdate')
            instance.employeetype = request.POST.get('employeetype')
            instance.employeeid = request.POST.get('employeeid')
            instance.dateissued = request.POST.get('dateissued')
            # instance.designation = request.POST.get('designation')

            instance.save()
            messages.success(request, 'Employee successfully created ',
                             extra_tags='alert alert-warning alert-dismissible show')
            return redirect('dashboard:employees')
        else:
            messages.error(request, 'Trying to create duplicate employees with a single user account ',
                           extra_tags='alert alert-warning alert-dismissible show')
            return redirect('dashboard:employeecreate')

    dataset = dict()
    form = EmployeeCreateForm()
    dataset['form'] = form
    dataset['title'] = 'register employee'
    return render(request, 'dashboard/employee_create.html', dataset)


from django.shortcuts import render, redirect
from django.contrib import messages
from employee.forms import FamilyCreateForm
from employee.models import Family
from django.contrib.auth.decorators import login_required


from django.contrib.auth.decorators import login_required
from employee.models import Employee


@login_required
def dashboard_family_create(request):
    if request.method == 'POST':
        form = FamilyCreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user

            # Associate the family record with the selected employee
            employee_id = request.POST.get('employee')
            if employee_id:
                instance.employee_id = employee_id

            instance.save()
            messages.success(request, 'Family information successfully created',
                             extra_tags='alert alert-warning alert-dismissible show')
            return redirect('dashboard:family')
        else:
            messages.error(request, 'Invalid input. Please check your information.',
                           extra_tags='alert alert-warning alert-dismissible show')
            return redirect('dashboard:familycreate')

    form = FamilyCreateForm()
    employees = Employee.objects.all()
    users = User.objects.all()
    dataset = {'form': form, 'title': 'Add Family Information', 'employees': employees, 'users': users}
    return render(request, 'dashboard/family_create.html', dataset)


#
# @login_required
# def dashboard_family_create(request):
#     if request.method == 'POST':
#         form = FamilyCreateForm(request.POST)
#         if form.is_valid():
#             instance = form.save(commit=False)
#             instance.user = request.user
#             instance.save()
#             messages.success(request, 'Family information successfully created',
#                              extra_tags='alert alert-warning alert-dismissible show')
#             return redirect('dashboard:family')
#
#         else:
#             messages.error(request, 'Invalid input. Please check your information.',
#                            extra_tags='alert alert-warning alert-dismissible show')
#             return redirect('dashboard:familycreate')
#
#     form = FamilyCreateForm()
#     employees = Employee.objects.all()  # Fetch all employees from the database
#     family = Family.objects.all()
#     users = User.objects.all()
#     dataset = {'form': form, 'title': 'Add Family Information', 'employees': employees, 'family':family, 'users':users}
#     return render(request, 'dashboard/family_create.html', dataset)

from django.shortcuts import render
from employee.models import Family
from django.contrib.auth.decorators import login_required


@login_required
def dashboard_family(request):
    family_info = Family.objects.filter(user=request.user).first()
    spouse = Family.objects.filter(user=request.user).first()
    status = Family.objects.filter(user=request.user).first()
    occupation = Family.objects.filter(user=request.user).first()
    context = {

templates/dashboard/create_leave.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

{% load crispy_forms_tags %}

{% block stylesheet %}
  #override-start {
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;
  }

  .alert-warning {
    background:#fd7b7b;
  }

  .alert-success {
    background-color: #82b72a;
  }

  .alert-success, .alert-warning {
    font-size:16px;
  }

  .sec {
    border:1px solid yellow;
    background:red;
  }

  .form-wrapper {
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    padding: 2%;
    background:#fff !important;
    padding-bottom:5%;
  }

  .btn-lg {
    padding:8px 30px;
  }
    .alert-warning {
    background: #ffeeba;
    color: red;
    border-color: #ffeeba;
    font-size: 14px; /* Reduce font size */
    border-radius: 4px; /* Rounded corners for a cleaner look */
    padding: 8px 12px; /* Smaller padding */
    margin: 10px 0; /* Margin to ensure it is not flush against the edge */
    position: absolute; /* Make it float at the top */
    top: 10px; /* Distance from the top of the page */
    left: 50%; /* Center horizontally */
    transform: translateX(-50%); /* Center horizontally with margin */
    width: auto; /* Adjust width automatically based on content */
    z-index: 1000; /* Ensure it appears on top of other elements */
}

{% endblock %}

{% block content %}
  <section class="content">
    <section class="container-fluid">

      <section class="form-wrapper">
        <section class="row">
          <section class="col col-lg-12 col-md-12 col-sm-12">
            {% if messages %}
              {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  {{ message }}
                  <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
              {% endfor %}
            {% endif %}
          </section>
        </section>

        <section class="row">
          <section class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
            <h3 class="title-h3">{{ title }}</h3>
          </section>
        </section>

        <section class="row">
          <section class="col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'dashboard:createleave' %}" method="POST">
              {% csrf_token %}
              {{ form | crispy }}
              {{ startdate }}
              {{ enddate }}
              <button type="submit" class="btn btn-primary btn-lg btn-block" {% if apply_leave_disabled %}disabled{% endif %}>
                Request Leave
              </button>
              {% if apply_leave_disabled %}
                <p class="alert alert-warning">You have exhausted your leave days. Please contact HR for more information.</p>
              {% endif %}
            </form>
          </section>
        </section>
      </section>

    </section> <!-- /container -->
  </section>
{% endblock %}

<script type="text/javascript">
{% block extrajs %}
// Optional JavaScript for additional checks or functionality
{% endblock %}
</script>

templates/dashboard/leaves_approved.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 width:200px;
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}

body {
	font-size:17px;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}


#stylebutton{
	background: #d04247 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#d04247;
}


.total-leaves-count p{
	font-size: 14px;
    color: #9d9d9d;
}


{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="text-shadow: 1px 0px rgba(0,0,0,0.11)">Approved Leaves</h4>
                		</div>
                		<section class="total-leaves-count">
                			{% if leave_list %}
                			<p>Total Approved Leaves - <span>{{ leave_list.count }}</span></p>
                			{% endif %}
                		</section>
                	
                		<table class="table">
							  <thead>
							    <tr>
							      <!-- <th scope="col">#</th> -->
							      <th scope="col"><b>User</b></th>
							      <th scope="col"><b>Type</b></th>
							      <th scope="col"><b>Leave Day(s) Remaining</b></th>
							      <th scope="col"><b>Status</b></th>
							      <th scope="col"><b>Actions</b></th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for leave in leave_list %}
							    <tr>

							      <td>{{ leave.user }}</td>
							      <td>{{ leave.leavetype }}</td>
								  <td>{{ total_leave_days_remaining }}</td>
							      <td><span class="badge badge-success" style="background-color:rgb(21, 172, 34); font-size: 14px;">{{ leave.status }}</span></td>

							      <td> 
							      	<a href="{% url 'dashboard:userleaveview' leave.id %}" style="color: #795548;">
							      	    <span>View &nbsp;</span>
							      	</a>
									{% if request.user.is_superuser %}
							      	
							        <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" style="color:#bd0404;">
							       	<span>Unapprove</span>
									{% endif %}
							        </a>

							      </td>
							    </tr>

							    {% endfor %}

							  </tbody>

						</table>
			
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>

<!-- pe-7s-back   <= -->

templates/dashboard/leaves_cancel.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 width:200px;
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}

body {
	font-size:17px;
}


#stylebutton{
	background: #d04247 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#d04247;
}


.total-leaves-count p{
	font-size: 14px;
    color: #9d9d9d;
}






{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="text-shadow: 1px 0px rgba(0,0,0,0.11)">Cancelled Leaves</h4>
                		</div>

                		<section class="total-leaves-count">
                			{% if leave_list_cancel %}
                			<p>Total cancelled leaves - <span>{{ leave_list_cancel.count }}</span></p>
                			{% endif %}
                		</section>
                	
                		<table class="table">
							  <thead>
							    <tr>
							      <!-- <th scope="col">#</th> -->
							      <th scope="col"><b>User</b></th>
							      <th scope="col"><b>Type</b></th>
							      <th scope="col"><b>Leave Day(s) Remaining</b></th>
							      <th scope="col"><b>Status</b></th>
							      <th scope="col"><b>Actions</b></th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for leave in leave_list_cancel %}
							    <tr>

							      <td>{{ leave.user }}</td>
							      <td>{{ leave.leavetype}}</td>
							      {% comment %} <td>{{ leave.leave_days }}</td> {% endcomment %}
								  <td>{{leave.total_leave_days_remaining}}</td>
							      <td>{{ leave.status }}</td>

							      <td> 
							      	<a href="{% url 'dashboard:userleaveview' leave.id %}" style="color: #795548;">
							      	    <span>View &nbsp;</span>
							      	</a>
							      	
							      	{% if not leave.is_approved %}
							      		<a href="{% url 'dashboard:userleaveuncancel' leave.id %}" style="color:#bd0404;">Undo Cancel</a>
							      	{% endif %}
							        
							      </td>
							    </tr>

							    {% endfor %}

							  </tbody>

						</table>
			
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>

<!-- pe-7s-back   <= -->